package com.rule

import com.ashokeit.dto.CitizenDto;
import com.ashokeit.dto.PlanDto;

rule "Is Children Count is More than 0"
  when
    ( citizen: CitizenDto(planName=="CCAP",kidsCount>0)) and 
    (plan: PlanDto())
  then
     plan.setPlanStatus("APPROVED");
     plan.setPlantStartDate("28-jan-2021");
     plan.setPalnEndDate("29-Mar-2023");
     plan.setBenitfitAmt(50000.0);
  end
  
rule "No Children"	
	when
	    ( citizen: CitizenDto(planName=="CCAP",kidsCount<=0)) and 
	    (plan: PlanDto())
	  then
	     plan.setPlanStatus("DN");
	     plan.setDenialReason("No kids Availble");
	  end